[package]
authors = ["K900 <me@0upti.me>", "Jake McGinty <jake@tonari.no>"]
categories = ["os::unix-apis"]
description = "High level bindings to the WireGuard embeddable C library"
edition = "2018"
license = "LGPL-2.1-or-later"
name = "wireguard-control"
readme = "README.md"
repository = "https://github.com/tonarino/innernet"
version = "1.5.1"

[dependencies]
base64 = "0.13"
hex = "0.4"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
wireguard-control-sys = { path = "../wireguard-control-sys", version = "1.5.1" }
netlink-sys = "0.7"
netlink-packet-core = "0.2"
netlink-packet-generic = "*"
netlink-packet-route = "0.8"
netlink-packet-wireguard = { git = "https://github.com/mcginty/netlink", branch = "wireguard-flags" }

[target.'cfg(not(target_os = "linux"))'.dependencies]
rand_core = "0.6"
curve25519-dalek = "4.0.0-pre.1"
