[package]
authors = ["Jake McGinty <me@jake.su>"]
edition = "2018"
license = "MIT"
name = "shared"
publish = false
version = "1.5.2"

[dependencies]
anyhow = "1"
atty = "0.2"
colored = "2.0"
dialoguer = { version = "0.9", default-features = false }
indoc = "1"
ipnetwork = { git = "https://github.com/mcginty/ipnetwork", rev = "393f2d89e41ac6c1c0d80a31fc0997c387a7f7ba" }
lazy_static = "1"
libc = "0.2"
log = "0.4"
publicip = { path = "../publicip" }
regex = "1"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
toml = "0.5"
ts-rs = { version = "6", features = ["serde-compat", "uuid-impl"] }
url = "2"
wireguard-control = { path = "../wireguard-control" }

[target.'cfg(target_os = "linux")'.dependencies]
netlink-packet-core = "0.2"
netlink-packet-route = "0.8"
netlink-sys = "0.7"
wireguard-control-sys = { path = "../wireguard-control-sys" }

[target.'cfg(target_os = "macos")'.dependencies]
nix = "0.23"
